/**
 * This client was automatically generated by RudderTyper. ** Do Not Edit **
 */

import Rudder

class RudderTyperAnalytics {
    static func sampleTrackEventName() {
        RudderTyperAnalytics.sampleTrackEventName(options: RSOption())
    }

    static func sampleTrackEventName(options: RSOption? = nil) {
        let properties = [String: Any]()

        RSClient.sharedInstance()?.track("Sample Track Event Name", properties: properties, options: RudderTyperUtils.addContextFields(options));
    }

}
