/**
 * This client was automatically generated by RudderTyper. ** Do Not Edit **
 */

#import <Foundation/Foundation.h>

@protocol RSRudderTyperSerializable

-(nonnull NSDictionary<NSString *, id> *) toDictionary;

@end
