/**
 * This client was automatically generated by RudderTyper. ** Do Not Edit **
 */

#import "RSRudderTyperAnalytics.h"
#import "RSRudderTyperUtils.h"

@implementation RSRudderTyperAnalytics

+ (void)sampleTrackEventName
{
    [RSRudderTyperAnalytics sampleTrackEventNameWithOptions:[[RSOption alloc]init]];
}

+ (void)sampleTrackEventNameWithOptions:(nullable RSOption *)options
{
    NSMutableDictionary *properties = [[NSMutableDictionary alloc] init];

    [[RSClient sharedInstance] track:@"Sample Track Event Name" properties:properties options:[RSRudderTyperUtils withRudderTyperContextFields:options]];
}

@end
