/**
 * This client was automatically generated by RudderTyper. ** Do Not Edit **
 */
#import <Foundation/Foundation.h>
#import <Rudder/Rudder.h>

@interface RSRudderTyperAnalytics : NSObject

+ (void)sampleTrackEventName;

+ (void)sampleTrackEventNameWithOptions:(nullable RSOption *)options;

@end
